import type { Metadata } from "next";
import { Provider } from "./Provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "BananaShop",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="antialiased">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
